server:
  port: 10086
spring:
  application:
    name: eurekaServer #???????
eureka:
  client:
    service-url:
      register-with-eureka: false   #????????eureka?
      fetch-registry: false         #???eureka?????
      defaultZone: http://127.0.0.1:10086/eureka/  #zhucefuwuzhong de fu wudizhi
